version: '3'
services:
  db:
    image: mysql:5.7
    container_name: prova2-mysql
    environment:
      - MYSQL_DATABASE=prova2_vendas
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - '3306:3306'
    network_mode: host
