package visao;


import controlador.DominioController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import modelo.Produto;
import modelo.Venda;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author jeanglazar
 */
public class Vendas extends javax.swing.JFrame {
    
    DominioController dominioController;

    /** Creates new form Locacao */
    public Vendas() {
        initComponents();
        try {
            dominioController = new DominioController();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
            System.exit(-1);
        }

//        // Mudar TEMA da janela para Windows
//        try {
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//            SwingUtilities.updateComponentTreeUI(this);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (Exception ex) {
//            Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
//        }        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtQtde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInsProduto = new javax.swing.JButton();
        txtPreco = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDtVenda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQtdeVendida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnInsVenda = new javax.swing.JButton();
        cmbProdutos = new javax.swing.JComboBox();
        txtTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnListarVendas = new javax.swing.JButton();
        btnListarVendasDia = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Vendas");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));
        jPanel1.setPreferredSize(new java.awt.Dimension(387, 100));

        jLabel1.setText("Nome");

        jLabel2.setText("Qtde");

        jLabel3.setText("Preço");

        btnInsProduto.setText("Inserir Produto");
        btnInsProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQtde)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(btnInsProduto)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsProduto))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendas"));

        jLabel4.setText("Produto");

        jLabel5.setText("Data Venda");

        jLabel6.setText("Qtde vendida");

        btnInsVenda.setText("Inserir Venda");
        btnInsVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsVendaActionPerformed(evt);
            }
        });

        cmbProdutos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cmbProdutosComponentShown(evt);
            }
        });

        jLabel7.setText("Valor Total");

        btnListarVendas.setText("Listar Vendas");
        btnListarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVendasActionPerformed(evt);
            }
        });

        btnListarVendasDia.setText("Listar Vendas Dia");
        btnListarVendasDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVendasDiaActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQtdeVendida)
                            .addComponent(cmbProdutos, 0, 161, Short.MAX_VALUE)
                            .addComponent(txtDtVenda)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarVendasDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnInsVenda))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtQtdeVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnListarVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListarVendasDia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProdutosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbProdutosComponentShown
         
    }//GEN-LAST:event_cmbProdutosComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
         carregarDropProdutos(cmbProdutos);
    }//GEN-LAST:event_formComponentShown

    private void btnInsProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsProdutoActionPerformed
         inserirProduto();
         carregarDropProdutos(cmbProdutos);
    }//GEN-LAST:event_btnInsProdutoActionPerformed

    private void btnInsVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsVendaActionPerformed
         inserirVenda();
    }//GEN-LAST:event_btnInsVendaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
         String id = JOptionPane.showInputDialog("Informe o id da venda: ");
         pesquisarVenda(Integer.parseInt(id));
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnListarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVendasActionPerformed
        try {
            JOptionPane.showMessageDialog(this, dominioController.listarTodos().toArray());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar vendas");
        } 
    
    }//GEN-LAST:event_btnListarVendasActionPerformed

    private void btnListarVendasDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVendasDiaActionPerformed
        try {
            JOptionPane.showMessageDialog(this, dominioController.listarVendasDia(txtDtVenda.getText()).toArray());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar vendas do dia");
        }
    }//GEN-LAST:event_btnListarVendasDiaActionPerformed

    /**
    * @param args the command line arguments
    */    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }
    
    public void pesquisarVenda(Integer id) {
        try {
            Venda venda = dominioController.buscarVenda(id);
            txtDtVenda.setText(venda.getDataVenda());
            txtQtdeVendida.setText(venda.getQtdeVenda().toString());
            txtTotal.setText(venda.getValorTotal().toString());
            Produto produto = dominioController.buscarProdutoPorId(venda.getProduto().getIdProduto());
            cmbProdutos.getModel().setSelectedItem(produto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar venda");
        }
    }
    
    public void buscarProduto(Integer id){
        
    }
    
    public void carregarDropProdutos(JComboBox drop){
        try {
            List<Produto> listaProdutos = dominioController.obterProdutos();
            drop.setModel(new DefaultComboBoxModel(listaProdutos.toArray()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar Produtos");
        }
    }
    
    public void limparCamposProduto(){
        txtNome.setText("");
        txtQtde.setText("");
        txtPreco.setText("");
    }
    
    public void limparCamposVenda(){
        txtDtVenda.setText("");
        txtQtdeVendida.setText("");
        txtTotal.setText("");
    }
    
    public void inserirVenda(){
        try {
            dominioController.inserirVenda(txtDtVenda.getText(), Integer.parseInt(txtQtdeVendida.getText()), Double.parseDouble(txtTotal.getText()), (Produto)cmbProdutos.getSelectedItem());
            JOptionPane.showMessageDialog(this, "Venda de " + cmbProdutos.getSelectedItem().toString() + " cadastrada com sucesso");
            limparCamposVenda();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir Venda");
        }
    }
    
    public void inserirProduto(){
        try {
            dominioController.inserirProduto(txtNome.getText(), Integer.parseInt(txtQtde.getText()), Double.parseDouble(txtPreco.getText()));
            limparCamposProduto();
            JOptionPane.showMessageDialog(this, "Produto " + txtNome.getText() + " inserido com sucesso");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir Produto");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsProduto;
    private javax.swing.JButton btnInsVenda;
    private javax.swing.JButton btnListarVendas;
    private javax.swing.JButton btnListarVendasDia;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox cmbProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDtVenda;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtde;
    private javax.swing.JTextField txtQtdeVendida;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
